"""
Quick setup utility to prepare a minimal CycleGAN dataset for custom traffic-sign swaps.

What it does:
1) Converts images from two input domains to square PNG files with a shared size.
2) Splits each domain into train/test folders.
3) Writes a Linux-friendly CycleGAN config that points to the generated folders.

Usage example:
python code/scripts/quick_try_custom_swap.py \
  --source-x datasets/diocles-acquisition-1 \
  --source-y /path/to/custom-signs \
  --work-dir datasets/custom_swap_quick
"""

from __future__ import annotations

import argparse
import json
import os
import random
import shutil
import subprocess
from pathlib import Path

VALID_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
NAME_PLACEHOLDER = "[name]"
# Resolve all relative CLI paths from the repository root, not shell CWD.
REPO_ROOT = Path(__file__).resolve().parents[2]


def find_images(path: Path) -> list[Path]:
    if not path.is_dir():
        raise FileNotFoundError(f"Invalid input path: {path}")

    files = [
        file_path
        for file_path in sorted(path.iterdir())
        if file_path.is_file() and file_path.suffix.lower() in VALID_EXTENSIONS
    ]

    if not files:
        raise RuntimeError(f"No supported images found in: {path}")

    return files


def ensure_ffmpeg() -> None:
    try:
        subprocess.run(["ffmpeg", "-version"], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception as exc:
        raise RuntimeError("ffmpeg is required but not available in PATH.") from exc


def convert_to_square_png(src: Path, dst: Path, image_size: int) -> None:
    # Scale so the shortest edge matches image_size, then center-crop to a square.
    scale_expr = (
        f"scale='if(gte(iw,ih),-2,{image_size})':'if(gte(iw,ih),{image_size},-2)',"
        f"crop={image_size}:{image_size},format=rgb24"
    )

    command = [
        "ffmpeg",
        "-y",
        "-loglevel",
        "error",
        "-i",
        str(src),
        "-vf",
        scale_expr,
        str(dst),
    ]
    subprocess.run(command, check=True)


def prepare_domain(raw_dir: Path, prepared_all_dir: Path, prefix: str, image_size: int, max_count: int) -> list[Path]:
    files = find_images(raw_dir)
    if max_count > 0:
        files = files[:max_count]

    prepared_all_dir.mkdir(parents=True, exist_ok=True)

    output_files: list[Path] = []
    for index, src in enumerate(files, start=1):
        dst = prepared_all_dir / f"{prefix}_{index:06d}.png"
        convert_to_square_png(src, dst, image_size)
        output_files.append(dst)

    return output_files


def split_files(files: list[Path], train_dir: Path, test_dir: Path, train_split: float, seed: int) -> tuple[int, int]:
    if not 0.0 < train_split < 1.0:
        raise ValueError("train_split must be in (0, 1).")

    train_dir.mkdir(parents=True, exist_ok=True)
    test_dir.mkdir(parents=True, exist_ok=True)

    rng = random.Random(seed)
    shuffled = list(files)
    rng.shuffle(shuffled)

    train_count = max(1, round(len(shuffled) * train_split))
    train_files = shuffled[:train_count]
    test_files = shuffled[train_count:]

    if not test_files:
        test_files = train_files[-1:]
        train_files = train_files[:-1]

    for src in train_files:
        shutil.copy2(src, train_dir / src.name)

    for src in test_files:
        shutil.copy2(src, test_dir / src.name)

    return len(train_files), len(test_files)


def build_config(work_dir: Path, image_size: int, epoch_count: int, batch_size: int) -> dict:
    output_root = work_dir / "output"

    return {
        "image_size": [image_size, image_size],
        "channel_count_x": 3,
        "channel_count_y": 3,
        "res_block_count": 6,
        "res_block_relu": False,
        "instance_norm_affine": False,
        "checkpoint_path": str(output_root / NAME_PLACEHOLDER / "checkpoints"),
        "description": "Quick custom swap config generated by quick_try_custom_swap.py",
        "class_mode": "none",
        "class_count": -1,
        "training_config": {
            "cycle_consistency_factor": 10.0,
            "image_buffer_size": 50,
            "batch_size": batch_size,
            "epoch_count": epoch_count,
            "learning_rate": 0.0002,
            "log_frequency": 50,
            "beta1": 0.5,
            "beta2": 0.999,
            "domain_x_path": str(work_dir / "train_x"),
            "domain_y_path": str(work_dir / "train_y"),
            "output_path": str(output_root / NAME_PLACEHOLDER / "output_training"),
            "summary_path": str(output_root / NAME_PLACEHOLDER / "summary"),
            "labels_x_path": "",
            "labels_y_path": "",
            "extension_x": ".png",
            "extension_y": ".png",
            "output": True,
            "summary": True,
            "augment": True,
            "augment_size": [image_size + 15, image_size + 15],
            "augment_flip": False,
            "class_loss_type": "",
        },
        "test_config": {
            "domain_x_path": str(work_dir / "test_x"),
            "domain_y_path": str(work_dir / "test_y"),
            "output_path": str(output_root / NAME_PLACEHOLDER / "output_test"),
            "labels_x_path": "",
            "labels_y_path": "",
            "extension_x": ".png",
            "extension_y": ".png",
        },
    }


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=4)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare a quick custom-swap CycleGAN setup.")
    parser.add_argument("--source-x", required=True, help="Path for domain X images (real signs).")
    parser.add_argument("--source-y", required=True, help="Path for domain Y images (custom signs).")
    parser.add_argument("--work-dir", default="datasets/custom_swap_quick", help="Output working directory.")
    parser.add_argument("--config-path", default="configs/custom_swap_quick_config.json", help="Destination config JSON path.")
    parser.add_argument("--image-size", type=int, default=128, help="Square output size used by the model.")
    parser.add_argument("--train-split", type=float, default=0.9, help="Train ratio in (0,1).")
    parser.add_argument("--epoch-count", type=int, default=30, help="Epoch count for quick experimentation.")
    parser.add_argument("--batch-size", type=int, default=2, help="Training batch size.")
    parser.add_argument("--max-per-domain", type=int, default=400, help="Maximum images loaded per domain; <=0 means all.")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for split reproducibility.")
    parser.add_argument("--clean", action="store_true", help="Delete work-dir before generating files.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    ensure_ffmpeg()

    source_x = Path(args.source_x)
    source_y = Path(args.source_y)
    work_dir = Path(args.work_dir)
    config_path = Path(args.config_path)

    if not source_x.is_absolute():
        source_x = Path(os.path.abspath(str(REPO_ROOT / source_x)))
    else:
        source_x = Path(os.path.abspath(str(source_x)))

    if not source_y.is_absolute():
        source_y = Path(os.path.abspath(str(REPO_ROOT / source_y)))
    else:
        source_y = Path(os.path.abspath(str(source_y)))

    if not work_dir.is_absolute():
        work_dir = Path(os.path.abspath(str(REPO_ROOT / work_dir)))
    else:
        work_dir = Path(os.path.abspath(str(work_dir)))

    if not config_path.is_absolute():
        config_path = Path(os.path.abspath(str(REPO_ROOT / config_path)))
    else:
        config_path = Path(os.path.abspath(str(config_path)))

    if args.clean and work_dir.exists():
        shutil.rmtree(work_dir)

    all_x = work_dir / "all_x"
    all_y = work_dir / "all_y"
    train_x = work_dir / "train_x"
    train_y = work_dir / "train_y"
    test_x = work_dir / "test_x"
    test_y = work_dir / "test_y"

    files_x = prepare_domain(source_x, all_x, "x", args.image_size, args.max_per_domain)
    files_y = prepare_domain(source_y, all_y, "y", args.image_size, args.max_per_domain)

    x_train_count, x_test_count = split_files(files_x, train_x, test_x, args.train_split, args.seed)
    y_train_count, y_test_count = split_files(files_y, train_y, test_y, args.train_split, args.seed)

    config = build_config(work_dir, args.image_size, args.epoch_count, args.batch_size)
    write_json(config_path, config)

    print("Quick setup complete.")
    print(f"Config: {config_path}")
    print(f"Domain X -> train/test: {x_train_count}/{x_test_count}")
    print(f"Domain Y -> train/test: {y_train_count}/{y_test_count}")
    print()
    print("Next commands:")
    print(f"export PYTHONPATH=\"{REPO_ROOT / 'code'}:$PYTHONPATH\"")
    print(f"python -m cyclegan.apps.train {config_path}")
    print(f"python -m cyclegan.apps.run {config_path} xy {test_x} {work_dir / 'out_xy'} -e .png")


if __name__ == "__main__":
    main()

